CREATE TABLE IF NOT EXISTS DiscordGuild (
        _INDEX INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
        _GUILD_ID VARCHAR(20) NOT NULL,
        _GUILD_REGISTER_DATE DATETIME NOT NULL,
        _GUILD_GMT INT4 DEFAULT 7 NOT NULL
);

